# Generated by Django 3.2.5 on 2022-02-14 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PsgPredictor',
            fields=[
                ('competition', models.IntegerField()),
                ('day', models.IntegerField()),
                ('venue', models.IntegerField()),
                ('opponent', models.IntegerField()),
                ('captain', models.IntegerField()),
                ('formation', models.IntegerField()),
                ('stamp', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.CharField(max_length=200)),
                ('win_or_lose', models.IntegerField()),
            ],
        ),
    ]
