# Generated by Django 3.2.5 on 2022-02-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_alter_result_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psgpredictor',
            name='captain',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='psgpredictor',
            name='competition',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='psgpredictor',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='psgpredictor',
            name='formation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='psgpredictor',
            name='opponent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='psgpredictor',
            name='venue',
            field=models.IntegerField(default=0),
        ),
    ]
